repos:
  - repo: local
    hooks:
      - id: pydantic-schema
        name: Generate & check Pydantic JSON Schema
        entry: python
        language: system
        pass_filenames: false
        args: [src/evalml/config.py, workflow/tools/config.schema.json]
