from pathlib import Path

import pytest
import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent


# Sentinel value for --regenerate-expected meaning "every parametrized config".
# Regenerating runs the full experiment per config, so it has to be asked for by
# name (or by this explicit opt-in) rather than being what a bare flag does.
REGENERATE_ALL = "all"

# Parametrize argument naming the config under test in tests/integration.
CONFIG_PARAM = "config_name"


def pytest_addoption(parser):
    parser.addoption(
        "--regenerate-expected",
        action="append",
        metavar="CONFIG",
        default=None,
        help=(
            "Integration metric tests: overwrite tests/integration/expected/CONFIG with "
            "the values this run produced instead of asserting against them, and "
            "deselect every other config. CONFIG is an exact config file name, e.g. "
            "--regenerate-expected=varda-single-1.0.yaml; repeat the option to "
            f"regenerate several, or pass --regenerate-expected={REGENERATE_ALL} for "
            "every config. A value is required: each config runs the full heavytest "
            "experiment, so regenerating all of them must be explicit. Omitted by "
            "default, so CI never regenerates."
        ),
    )


def config_under_test(item):
    """The config file name a parametrized item runs, or None for other tests."""
    callspec = getattr(item, "callspec", None)
    return callspec.params.get(CONFIG_PARAM) if callspec else None


def pytest_collection_modifyitems(config, items):
    """Validate --regenerate-expected against the collected configs and deselect
    the ones not named.

    The flag matches config names exactly. Selecting with `-k` instead would be
    substring-based: `-k varda-single` also selects varda-single-2.0.yaml and
    `-k forecasters-ich1` also selects forecasters-ich1-oper.yaml, so a short name
    could silently overwrite a reference that was not meant to be touched, at
    hours of GPU time per config.
    """
    requested = config.getoption("--regenerate-expected")
    if not requested:
        return

    collected = {c for c in map(config_under_test, items) if c is not None}
    if REGENERATE_ALL in requested:
        return

    unknown = [name for name in requested if name not in collected]
    if unknown:
        raise pytest.UsageError(
            f"--regenerate-expected: unknown config(s) {unknown}. Pass an exact config "
            f"file name — one of {sorted(collected)} — or '{REGENERATE_ALL}' to "
            f"regenerate every config. A partial name is deliberately not accepted, so "
            f"a similarly named config cannot be regenerated by accident."
        )

    # Narrow only the config-parametrized items; anything else selected on the
    # command line is left alone.
    keep, deselected = [], []
    for item in items:
        name = config_under_test(item)
        (keep if name is None or name in requested else deselected).append(item)
    if deselected:
        config.hook.pytest_deselected(items=deselected)
        items[:] = keep


def pytest_collection_finish(session):
    """Refuse to run if --regenerate-expected selected nothing.

    Checked here rather than in pytest_collection_modifyitems above, which runs
    *before* pytest applies `-m`/`-k`: forgetting `-m heavytest` otherwise leaves
    the metric tests deselected and the run reports a green "N passed" having
    regenerated nothing at all.
    """
    if not session.config.getoption("--regenerate-expected"):
        return
    if any(config_under_test(item) is not None for item in session.items):
        return
    raise pytest.UsageError(
        "--regenerate-expected selected no config-parametrized metric test, so there "
        "is nothing to regenerate. The metric tests are marked heavytest and are "
        "deselected by default — select them explicitly, e.g. `pytest "
        "tests/integration/test_configs.py -m heavytest --regenerate-expected=<config>`."
    )


@pytest.fixture
def regenerate_expected(request):
    """True when this test's config was named by --regenerate-expected.

    Checked per config rather than treating the flag as a global boolean, so a
    config that was not asked for cannot overwrite its reference even if the
    deselection in tests/integration/conftest.py were bypassed.
    """
    requested = request.config.getoption("--regenerate-expected")
    if not requested:
        return False
    if REGENERATE_ALL in requested:
        return True
    return config_under_test(request.node) in requested


@pytest.fixture
def example_config():
    configfile = PROJECT_ROOT / "tests/integration/configs/varda-single-1.0.yaml"
    with open(configfile, "r") as f:
        config = yaml.safe_load(f)
    return config
