# https://github.com/ecmwf/anemoi-inference/blob/0a1e518a129e7960e60e84885da6bca5a13dec58/src/anemoi/inference/commands/inspect.py
import argparse
import json
import sys

CORE = ("models", "training", "graphs")


SKIP = {"anemoi-training", "databricks-connect"}

SKIP |= set(sys.stdlib_module_names) | set(sys.builtin_module_names)

PACKAGES = {
    "sklearn": "scikit-learn",
    "attr": "attrs",
    "google-protobuf": "protobuf",
}


def main(args):
    with open(args.metadata, "r") as f:
        md = json.load(f)["provenance_training"]
    print("# This file is automatically generated from a checkpoint.")
    print("# Python:", md.get("python"))

    distribution_names = md.get("distribution_names", {})
    distribution_names.update(PACKAGES)

    pypi_requirements = {}
    git_requirements = {}

    for k, v in md.get("module_versions", {}).items():
        if k.startswith("_"):
            continue
        if v[0].isdigit():
            v = [x for x in v.split(".") if x.isdigit()]
            v = ".".join(v)
            k = k.replace(".", "-")
            if "anemoi" in k or "torch" in k:
                pypi_requirements[distribution_names.get(k, k)] = v

    for k, v in md.get("git_versions", {}).items():
        if not k.startswith("anemoi."):
            continue

        sha1 = v.get("git", {}).get("sha1")

        if not sha1:
            continue

        what = k.split(".")[-1]
        if what in CORE:
            url = f"git+https://github.com/ecmwf/anemoi-core@{sha1}#subdirectory={what}"
        else:
            url = f"git+https://github.com/ecmwf/anemoi-{what}@{sha1}"

        k = k.replace(".", "-")
        git_requirements[k] = url

    if git_requirements:
        print("")
        print("# Git requirements:")
        print("")

    for k, v in sorted(git_requirements.items()):
        if k in SKIP:
            continue

        version = pypi_requirements.pop(k, None)
        if version:
            print(f"# {k}=={version}")
        print(v)

    if pypi_requirements:
        print("")
        print("# PyPI requirements:")
        print("")

    for k, v in sorted(pypi_requirements.items()):
        if k in SKIP:
            continue

        print(f"{k}=={v}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("metadata", help="Path to the metadata JSON file")
    args = parser.parse_args()
    main(args)
