description: |
  This study contains the best models for the COSMO-2 deterministic emulator.
  The baseline model is the COSMO-E control run.
# init_times: TODO: init_times override for study
  # start: 2020-01-01T12:00
  # end: 2020-01-10T00:00
  # frequency: 18h
baselines:
  - COSMO-E
experiments:
  - stage_D-cerra-N320
  - stage_D-cerra-N320-low_lam