runner: time_interpolator

input:
  test:
    use_original_paths: true

output:
  tee:
    outputs:
      - extract_lam:
          output:
            assign_mask:
              mask: "source0/trimedge_mask"
              output:
                grib:
                  path: grib/{dateTime}_{step:03}.grib
                  encoding:
                    typeOfGeneratingProcess: 2
                  templates:
                    samples: resources/templates_index_cosmo.yaml

verbosity: 1
allow_nans: true
output_frequency: "1h"
