input:
  test:
    use_original_paths: true

allow_nans: true

output:
  grib:
    path: grib/{date}{time:04}_{step:03}.grib
    negative_step_mode: skip
    # templates:
    #   samples: resources/templates_index_global-ea.yaml

write_initial_state: true

patch_metadata:
  config:
    dataloader:
      test:
        datasets:
          data:
            dataset_config:
              dataset: /store_new/mch/msopr/ml/datasets/aifs-ea-an-oper-0001-mars-o96-1979-2024-1h-v3-with-era51.zarr/
            start: null
            end: null