input:
  test:
    use_original_paths: true

allow_nans: true

post_processors:
  - accumulate_from_start_of_forecast: # accumulate tp from start of forecast
      accumulations:
        - tp
  - forward_transform_filter:
      rescale:
        scale: 1000 # convert units from m to kg m-2
        offset: 0
        param: tp

output:
  tee:
    - grib:
        path: grib/{dateTime}_{step:03}.grib
        encoding:
          typeOfGeneratingProcess: 2
        templates:
          samples: resources/templates_index_cosmo.yaml
        post_processors:
          - extract_mask: # removes global points
              mask: "source0/cutout_mask"
              as_slice: true
    - grib:
        path: grib/ifs-{dateTime}_{step:03}.grib
        encoding:
          typeOfGeneratingProcess: 2
        templates:
          samples: resources/templates_index_ifs.yaml
        post_processors:
        - extract_mask: # removes lam points
            mask: "lam_0/cutout_mask"
            as_slice: true
            inverse: true
        - assign_mask: # fill local/global overlapping points with nan
            mask: "global/cutout_mask"

write_initial_state: true
