lead_time: 120h
write_initial_state: true
allow_nans: true

env:
  ANEMOI_INFERENCE_NUM_CHUNKS: 8 # OOM error if not set

# inputs
input:
  test:
    use_original_paths: true


post_processors:
  - accumulate_from_start_of_forecast: # accumulate tp from start of forecast
      accumulations:
        - tp
  - forward_transform_filter:
      rescale:
        scale: 1000 # convert units from m to kg m-2
        offset: 0
        param: tp

output:
  tee:
    - grib:
        path: grib/{date}{time:04}_{step:03}.grib
        encoding:
          typeOfGeneratingProcess: 2
        templates:
          samples: resources/templates_index_icon.yaml
        post_processors:
          - extract_mask: # removes global points
              mask: "lam_0/cutout_mask"
              as_slice: true
    - grib:
        path: grib/ifs-{date}{time:04}_{step:03}.grib
        encoding:
          typeOfGeneratingProcess: 2
        templates:
          samples: resources/templates_index_ifs.yaml
        post_processors:
        - extract_mask: # removes lam points
            mask: "lam_0/cutout_mask"
            as_slice: true
            inverse: true
        - assign_mask: # fill local/global overlapping points with nan
            mask: "global/cutout_mask"
        modifiers:
          - patches:
            - variable:
                U_10M: {"param": 165, "shortName": "10u"}
                10u: {"param": 165, "shortName": "10u"}
                V_10M: {"param": 166, "shortName": "10v"}
                10v: {"param": 166, "shortName": "10v"}
                TD_2M: {"param": 167, "shortName": "2d"}
                2d: {"param": 168, "shortName": "2d"}
                T_2M: {"param": 167, "shortName": "2t"}
                2t: {"param": 167, "shortName": "2t"}
                FR_LAND: {"param": 172, "shortName": "lsm"}
                lsm: {"param": 172, "shortName": "lsm"}
                PMSL: {"param": 151, "shortName": "msl"}
                msl: {"param": 151, "shortName": "msl"}
                PS: {"param": 134, "shortName": "sp"}
                sp: {"param": 134, "shortName": "sp"}
                SSO_SIGMA: {"param": 163, "shortName": "slor"}
                slor: {"param": 163, "shortName": "slor"}
                SSO_STDH: {"param": 160, "shortName": "sdor"}
                sdor: {"param": 160, "shortName": "sdor"}
                TOT_PREC: {"param": 228, "shortName": "tp"}
                tp: {"param": 228, "shortName": "tp"}
                z: {"param": 129, "shortName": "z"}
                "^q_(\\d+)$": {"param": 133, "shortName": "q"}
                "^t_(\\d+)$": {"param": 130, "shortName": "t"}
                "^u_(\\d+)$": {"param": 131, "shortName": "u"}
                "^v_(\\d+)$": {"param": 132, "shortName": "v"}
                "^w_(\\d+)$": {"param": 135, "shortName": "w"}
                "^z_(\\d+)$": {"param": 129, "shortName": "z"}

patch_metadata: resources/sgm-ich1-patch_metadata.yaml
