# yaml-language-server: $schema=../workflow/tools/config.schema.json
description: |
  Evaluate skill of ECMWF AIFS-single.

config_label: AIFS-single-1.1


dates:
  start: 2024-01-01T00:00
  end: 2024-01-01T00:00
  frequency: 24h

runs:
  - forecaster:
      checkpoint: https://huggingface.co/ecmwf/aifs-single-1.1/resolve/main/aifs-single-mse-1.1.ckpt
      label: AIFS-single-1.1
      steps: 0/120/6
      config: resources/inference/configs/aifs-single-forecaster.yaml
      extra_requirements:
        - torch-geometric==2.4.0
        - anemoi-inference==0.11.1
        - anemoi-models==0.5.0
        - https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.6cxx11abiFALSE-cp312-cp312-linux_x86_64.whl
      disable_local_eccodes_definitions: true

truth:
  label: ERA5-o96
  root: /store_new/mch/msopr/ml/datasets/aifs-ea-an-oper-0001-mars-o96-1979-2024-1h-v3-with-era51.zarr

lapse_rate_correction: false

experiment:
  params:
    - T_2M
    - TD_2M
    - SP_10M
    - TOT_PREC
  dashboard:
    stratification:
      # - region
      # - init_hour
      - season
  stratification:
    regions:
      - global: [-180, 180, -90, 90]

locations:
  output_root: output/

profile:
  executor: slurm
  global_resources:
    gpus: 16
  default_resources:
    slurm_partition: "postproc"
    cpus_per_task: 1
    mem_mb_per_cpu: 1800
    runtime: "1h"
    gpus: 0
  jobs: 50
