experiment:
  run_id: 7c58e59d24e949c9ade3df635bbd37e2
  name: prova
lead_time: 120h

default_config: config.yaml

execution:
  run_group_size: 4

init_times: 
  start: 2020-01-01T12:00
  end: 2020-01-30T00:00
  frequency: 18h

locations:
  output_root: output
  mlflow_uri: 
    - https://servicedepl.meteoswiss.ch/mlstore
    - https://mlflow.ecmwf.int
