# yaml-language-server: $schema=../workflow/tools/config.schema.json
description: |
  This is an experiment to do blabla.

dates:
  start: 2020-01-01T12:00
  end: 2020-01-10T00:00
  # end: 2020-03-30T00:00
  frequency: 54h

lead_time: 120h

runs:
  # - interpolator:
  #     run_id: 9c18b90074214d769b8b383722fc5a06
  #     label: Interpolator (M-1 forecaster)
  #     forecaster:
  #       run_id: d0846032fc7248a58b089cbe8fa4c511
  - forecaster:
      run_id: 2f962c89ff644ca7940072fa9cd088ec
      label: Stage D - N320 global grid with CERRA finetuning
  - forecaster:
      run_id: d0846032fc7248a58b089cbe8fa4c511
      label: M-1 forecaster

baseline: COSMO-E

execution:
  run_group_size: 4

locations:
  output_root: output/
  mlflow_uri:
    - https://service.meteoswiss.ch/mlstore
    - https://servicedepl.meteoswiss.ch/mlstore
    - https://mlflow.ecmwf.int

verification:
  valid_every: 12

profile:
  executor: slurm
  default_resources:
    slurm_partition: "postproc"
    cpus_per_task: 1
    mem_mb_per_cpu: 1800
    runtime: "1h"
  jobs: 10
