# yaml-language-server: $schema=../workflow/tools/config.schema.json
description: |
  Evaluate skill of ICON-CH1 forecasters from experiment 602 (excluding stage_B, AE, multi_dataset_icon_era5).

dates:
  start: 2025-03-01T00:00
  end: 2025-05-31T00:00
  frequency: 24h


runs:

  - forecaster:
      inference_resources: 
          slurm_partition: normal-shared
      checkpoint: https://service.meteoswiss.ch/mlstore#/experiments/602/runs/fd63e17043014af59170c7beca516b95
      label: stage_E_realch1
      steps: 0/120/6
      config: resources/inference/configs/sgm-multidataset-forecaster-global-ich1-oper.yaml
      extra_requirements:
        - git+https://github.com/ecmwf/anemoi-inference.git@b9aaee5df86614cad9d8d08b76876a4be4e980db


baselines:
  - baseline:
      baseline_id: ICON-CH1-EPS
      label: ICON-CH1-ctrl
      root: /scratch/mch/cmerker/ICON-CH1-EPS
      steps: 0/33/6
  - baseline:
      baseline_id: ICON-CH2-EPS
      label: ICON-CH2-ctrl
      root: /scratch/mch/cmerker/ICON-CH2-EPS
      steps: 0/120/6

truth:
  label: KENDA-CH1
  root: /store_new/mch/msopr/ml/datasets/mch-ich1-1km-2024-2025-1h-pl13-v1.0.zarr

stratification:
  regions:
    - jura
    - mittelland
    - voralpen
    - alpennordhang
    - innerealpentaeler
    - alpensuedseite
  root: /scratch/mch/bhendj/regions/Prognoseregionen_LV95_20220517

locations:
  output_root: /scratch/mch/lfrey/2025_SEN_eval_ML/software/evalml/xyz_abc/evalml/output/

profile:
  executor: slurm
  global_resources:
    gpus: 16
  default_resources:
    slurm_partition: "postproc"
    cpus_per_task: 1
    mem_mb_per_cpu: 1800
    runtime: "1h"
    gpus: 0
  jobs: 50
  batch_rules:
    plot_forecast_frame: 32

spatial_verification:
  params:
    - T_2M
    - TD_2M
    - U_10M
    - V_10M
    - SP_10M
    - PS
    - PMSL
    - TOT_PREC
  leadtimes:
    - 6
    - 24
  metrics:
    - BIAS
    - RMSE
  regions:
    - switzerland
    - centraleurope
  seasons:
    - all
