description: HiRAD co2 test evaluation

dates:
  - 2023-01-15T00:00
  - 2023-01-15T06:00
  - 2023-01-15T12:00
  - 2023-01-15T18:00
  # add more timestamps as needed

runs:
  - baseline:
      label: ICON-CH2-EPS
      root: /store_new/mch/msopr/osm/ICON-CH2-EPS
      steps: 0/120/6
  - baseline:
      label: HiRAD
      root: /scratch/mch/mmcgloho/grib/
      steps: "0/0/1"

truth:
  label: KENDA-CH1
  root: /store_new/mch/msopr/ml/datasets/mch-ich1-1km-2024-2025-1h-pl13-v1.0.zarr

locations:
  output_root: output/

experiment:
  stratification:
    regions: []
  dashboard:
    stratification:
      - season

profile:
  executor: slurm
  global_resources:
    gpus: 1
  default_resources:
    slurm_partition: postproc
    cpus_per_task: 1
    mem_mb_per_cpu: 1800
    runtime: "1h"
    gpus: 0
  jobs: 10