# yaml-language-server: $schema=../workflow/tools/config.schema.json
description: |
  Evaluate skill of new time-interpolator (trained on ICON-REA-L, fine-tuned on KENDA-ICON-CH1)
  driven by ICON-CH1 stage_E forecaster with subgrid orography, using anemoi-inference patch from
  issue #482.

dates:
  start: 2025-03-01T00:00
  end: 2025-03-03T00:00
  frequency: 24h


runs:
  - interpolator:
      inference_resources:
          slurm_partition: normal-shared
      # for checkpoints trained on a different HPC, using mlflow doesn't work due to difference in
      # paths, so we directly specify the checkpoint path here
      checkpoint: /store_new/mch/msopr/ml/tmp/inference-last.ckpt
      label: Varda-Single
      steps: 0/120/1
      config: resources/inference/configs/sgm-interpolator-global_trimedge_multi.yaml
      forecaster:
        checkpoint: https://service.meteoswiss.ch/mlstore#/experiments/602/runs/c30490b6ba064e4db03b430f3a2595ad
        config: resources/inference/configs/sgm-multidataset-forecaster-global-ich1-oper.yaml
        steps: 0/120/6
        extra_requirements:
          - git+https://github.com/ecmwf/anemoi-inference.git@e369b1a90313e9701db13f63364a467aa281cf36
      extra_requirements:
        - git+https://github.com/ecmwf/anemoi-inference.git@e369b1a90313e9701db13f63364a467aa281cf36
        # pinned anemoi-datasets because of ecmwf/anemoi-utils#284, can be removed when fixed
        - anemoi-datasets==0.5.35
  - baseline:
      baseline_id: ICON-CH2-EPS
      label: ICON-CH2-ctrl
      root: /store_new/mch/msopr/ml/ICON-CH2-EPS
      steps: 0/120/1
  - baseline:
      baseline_id: ICON-CH1-EPS
      label: ICON-CH1-ctrl
      root: /store_new/mch/msopr/ml/ICON-CH1-EPS
      steps: 0/33/1

truth:
  label: KENDA-CH1
  root: /store_new/mch/msopr/ml/datasets/mch-ich1-1km-2024-2025-1h-pl13-v1.0.zarr

stratification:
  regions:
    - jura
    - mittelland
    - voralpen
    - alpennordhang
    - innerealpentaeler
    - alpensuedseite
  root: /scratch/mch/bhendj/regions/Prognoseregionen_LV95_20220517

dashboard:
  stratification:
    # - region
    # - init_hour
    - season

locations:
  output_root: output/

profile:
  executor: slurm
  global_resources:
    gpus: 16
  default_resources:
    slurm_partition: "postproc"
    cpus_per_task: 1
    mem_mb_per_cpu: 1800
    runtime: "1h"
    gpus: 0
  jobs: 50
  batch_rules:
    plot_forecast_frame: 32
