# yaml-language-server: $schema=../workflow/tools/config.schema.json
description: |
  Basic config for showcasing M-1 forecaster.

dates:
  - 2020-02-03T00:00 # Storm Petra
  - 2020-02-07T00:00 # Storm Sabine
  - 2020-10-01T00:00 # Storm Brigitte

runs:
  - forecaster:
      mlflow_id: d0846032fc7248a58b089cbe8fa4c511
      label: M-1 forecaster
      config: resources/inference/configs/forecaster_with_global.yaml
      steps: 0/120/6

baselines:
  - baseline:
      baseline_id: COSMO-E
      label: COSMO-E
      root: /store_new/mch/msopr/ml/COSMO-E
      steps: 0/120/6

analysis:
  label: COSMO KENDA
  analysis_zarr: /scratch/mch/fzanetta/data/anemoi/datasets/mch-co2-an-archive-0p02-2015-2020-6h-v3-pl13.zarr

locations:
  output_root: output/
  mlflow_uri:
    - https://servicedepl.meteoswiss.ch/mlstore
    - https://mlflow.ecmwf.int

profile:
  executor: slurm
  global_resources:
    gpus: 15
  default_resources:
    slurm_partition: "postproc"
    cpus_per_task: 1
    mem_mb_per_cpu: 1800
    runtime: "1h"
    gpus: 0
  jobs: 50
  batch_rules:
    plot_forecast_frame: 32
