# yaml-language-server: $schema=../workflow/tools/config.schema.json
description: |
  Evaluation of Varda-Single version 1.0.

dates:
  start: 2025-01-01T00:00
  end: 2025-12-31T18:00
  frequency: 54h

runs:
  - temporal_downscaler:
      checkpoint: /scratch/mch/miccatta/ICON_interpolator_checkpoints/checkpoint_stage-C-interpolator-n320-6hto1h-reduced-variables/f9279244ed6f4c458597bdcf335ab36f/inference-last.ckpt
      label: Varda-Single
      steps: 0/120/1
      config: resources/inference/configs/sgm-temporal-downscaler-global_trimedge_multi.yaml
      extra_requirements:
        - anemoi-datasets==0.5.35
        # - anemoi-inference==0.11.0
      forecaster:
        checkpoint: https://service.meteoswiss.ch/mlstore#/experiments/602/runs/c30490b6ba064e4db03b430f3a2595ad
        config: resources/inference/configs/sgm-multidataset-forecaster-global-ich1-oper.yaml
        steps: 0/120/6
  - baseline:
      label: INCA
      root: /store_new/mch/msclim/INCA
      steps: 0/6/1
  - baseline:
      label: ICON-CH1-CTRL
      root: /store_new/mch/msopr/osm/ICON-CH1-EPS
      steps: 0/33/1
      member: control
  - baseline:
      label: ICON-CH1-EPS mean
      root: /store_new/mch/msopr/osm/ICON-CH1-EPS
      steps: 0/33/1
      member: mean
  - baseline:
      label: ICON-CH2-CTRL
      root: /store_new/mch/msopr/osm/ICON-CH2-EPS
      steps: 0/120/1
      member: control
  - baseline:
      label: ICON-CH2-EPS mean
      root: /store_new/mch/msopr/osm/ICON-CH2-EPS
      steps: 0/120/1
      member: mean

truth:
  label: KENDA-CH1
  root: /store_new/mch/msopr/ml/datasets/mch-ich1-1km-2024-2025-1h-pl13-v1.0.zarr

experiment:
  params:
    - T_2M
    - TD_2M
    - U_10M
    - V_10M
    - TOT_PREC
  stratification:
    regions:
      - jura
      - mittelland
      - alpennordhang
      - innerealpentaeler
      - alpensuedseite
    root: /scratch/mch/bhendj/regions/Prognoseregionen_LV95_20220517
  thresholds:
    TOT_PREC:
      gt: [0.0, 1, 5]
    U_10M:
      gt: [2.5, 5.0, 10.0]
    V_10M:
      gt: [2.5, 5.0, 10.0]
    T_2M:
      lt: [273.15]
      gt: [288.15, 298.15]
  dashboard:
    stratification:
      # - region
      # - init_hour
      - season
  scorecards:
    enabled: true
    sections:
      nowcasting:
        baseline: INCA
        lead_times: "0/6/1"
        stratification: region
        variables:
          - "U_10M:RMSE,R2,ETS"
          - "T_2M:RMSE,R2,ETS"
          - "TOT_PREC:RMSE,R2,ETS"
      short_range:
        baseline: ICON-CH1-CTRL
        lead_times: "6/33/6"
        stratification: region
        variables:
          - "U_10M:RMSE,R2,ETS"
          - "T_2M:RMSE,R2"
          - "TOT_PREC:RMSE,R2,ETS"
      medium_range:
        baseline: ICON-CH2-CTRL
        lead_times: "24/120/24"
        stratification: region
        variables:
          - "U_10M:RMSE,R2,ETS"
          - "T_2M:RMSE,R2"
          - "TOT_PREC:RMSE,R2,ETS"



locations:
  output_root: output/

profile:
  executor: slurm
  global_resources:
    gpus: 16
  default_resources:
    slurm_partition: "postproc"
    cpus_per_task: 1
    mem_mb_per_cpu: 1800
    runtime: "1h"
    gpus: 0
    account: s83
  jobs: 50
